name: CI

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: NPM install and build
        shell: "bash"
        run: |
          cd ./web
          npm install
          npm run build
      
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./web/dist/public/"
